#!/bin/bash

help() {
    echo "
workon: Navigate and prepare project to work on

Usage: workon $project

Options:
	--help, show this message
	--list, list available projects
	--swap, stops docker containers and starts project containers  
        --up, like swap, except only starts project containers
"
    return 1
}

navigate() {
    dev_dir="$HOME"
    project_dirs="R Dev Dev/WebDev"
    for dir in $project_dirs;
    do
	if [ -d $dev_dir'/'$dir'/'$1 ]; then
	    cd $dev_dir'/'$dir'/'$1
	    if [[ ! -z "$2" ]] && [[ -f $dev_dir'/'$dir'/'$1'/docker-compose.yml' ]]; then
		docker-compose up -d
	    fi
	    return 1
	fi
    done
    echo "$1 does not exist"
    return 1
}

main() {
    dir="$1"
    if [ ! -z "$2" ]; then
	dir="$2"
    fi
    if [ -z "$dir" ]; then
	help
	return 1
    fi
    case $1 in
	--help)
	    help
	    return
	    ;;
	--list)
	    echo "listing..."
	    curdir="$(pwd)"
	    cd "$HOME/R"
	    for i in $(ls -d */); do echo ${i%%/}; done
	    cd "$curdir"
	    return 1
	    ;;
	--swap)
	    echo "stopping all docker containers..."
	    docker stop $(docker ps -aq)
	    navigate "$dir" "swap"
	    return 1
	    ;;
	--up)
	    navigate "$dir" "up"
	    return 1
	    ;;
    esac

    navigate "$dir"
}

main "$1" "$2"
